# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    - CONFIG=osx_c_compilerclang
    - CONFIG=osx_c_compilertoolchain_c

  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "HHddXD2OvCI487K5Zx0C0CzfkIA+xMiJhesqtGBo3LnoW4juSZ/r2gVkohpoGwzqvgN9zbq9FgqMqBhaQYTAF/JDeWbS6ewMhwdeawbJPwaIoSqDRsVRdeW7UYb5GPSgvm18BTwV4c+OQNSG4qNT4jh3fKAwC8kSC3J08nWM02/y4ekB/58Qni/JrYsmtbkvcYrkHhaG8d1Hf1dQCSjEePGwC/Rv6DHxXDXksWHPEC+x6E176qSZhOODvkZ96/bIgzicjI7ibuFpNw1InIWf/njMZPYSUnAtwCg8isJK5UXzt+wOw5hsn/Eudlj990hpkpdPiWeMHmx01ADFfHfUczt7IsZ6owsH3up6RwC6T6LUNAbMM4GuiIziqOmNtdcs3LB6SWBD0rLuAMSHeg9AyfuoLhzZ8o4DytfdlwrkHyrxkAlz5G1SRolamle/NqiZzmxRTodW2fMLu2DjpNI5dWdeAxI/VVMIhBQ2wOGp15zifH8PJNMW9BtdGA5f5lQ9aHw4xUlR8qoXCmhVMc/e3aueFLx8ZaYXoYw1eflbDYkisgfpMCWIjIpLFCDiZ9XPq354gBY3FcesNF6D3SuApxlVBnOg9yelFagivGrXVoqTPNoogis+zP5zyqNjs8OynnyQ4eIJlQxKMdSwaXsqg7ZC78KgYFy0ijsEOc0mfRI="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-ci-setup-feedstock/branch2.0/recipe/conda_forge_ci_setup/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root

      conda install --yes --quiet conda-forge::conda-forge-ci-setup=2
      setup_conda_rc ./ ./recipe ./.ci_support/${CONFIG}.yaml

      source run_conda_forge_build_setup

    # compiler cleanup
    - |
      mangle_compiler ./ ./recipe ./.ci_support/${CONFIG}.yaml

script:
  # generate the build number clobber
  - make_build_number ./ ./recipe ./.ci_support/${CONFIG}.yaml
  - conda build ./recipe -m ./.ci_support/${CONFIG}.yaml --clobber-file ./.ci_support/clobber_${CONFIG}.yaml
  - upload_package ./ ./recipe ./.ci_support/${CONFIG}.yaml
