appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: HHddXD2OvCI487K5Zx0C0CzfkIA+xMiJhesqtGBo3LnoW4juSZ/r2gVkohpoGwzqvgN9zbq9FgqMqBhaQYTAF/JDeWbS6ewMhwdeawbJPwaIoSqDRsVRdeW7UYb5GPSgvm18BTwV4c+OQNSG4qNT4jh3fKAwC8kSC3J08nWM02/y4ekB/58Qni/JrYsmtbkvcYrkHhaG8d1Hf1dQCSjEePGwC/Rv6DHxXDXksWHPEC+x6E176qSZhOODvkZ96/bIgzicjI7ibuFpNw1InIWf/njMZPYSUnAtwCg8isJK5UXzt+wOw5hsn/Eudlj990hpkpdPiWeMHmx01ADFfHfUczt7IsZ6owsH3up6RwC6T6LUNAbMM4GuiIziqOmNtdcs3LB6SWBD0rLuAMSHeg9AyfuoLhzZ8o4DytfdlwrkHyrxkAlz5G1SRolamle/NqiZzmxRTodW2fMLu2DjpNI5dWdeAxI/VVMIhBQ2wOGp15zifH8PJNMW9BtdGA5f5lQ9aHw4xUlR8qoXCmhVMc/e3aueFLx8ZaYXoYw1eflbDYkisgfpMCWIjIpLFCDiZ9XPq354gBY3FcesNF6D3SuApxlVBnOg9yelFagivGrXVoqTPNoogis+zP5zyqNjs8OynnyQ4eIJlQxKMdSwaXsqg7ZC78KgYFy0ijsEOc0mfRI=}
