travis:
  secure:
    BINSTAR_TOKEN: Ejxhe38gPpKlgZlL5RNWQPW3yQibyWigkL3DliNOub458lfsvjvcEYqLeCBwIHo1c/rz+8fN51C/veCOIIbl47mnoaJ07WSSaAoj1guMf5+euwzxWx1Ut5YJlcSjhY/VMF0sTkGO80Qb1jWD6dhApsoW7jz7j85/EkmL5drSumQXfqj63/Vii1yD8RVoDDI9t4gFYuEZ/T+xKMdSmdBKmXAAoRMowqp1jby6sn0kOYOY3hNJOPZJyJpDuhUKSajYKvpRVuttmkgpHyuxOoKPYNa2I16Z0urABad/mhjD8Okmdj1rtW+PW5En6mhyZkPr5wIVt5XhQFYJH/fpv0G13nRF750jr7A8ZJzkj8RBSZc5BvnnfeAVoawzIBQNF0/Pzs5nT/15Yw1PPYQXt+YG6oW+yfOUBKFdtQlKlgN6IagZ/CXhrWhJiyfI8XrOU007fnXipqS7D7VSnbrYq5SuolUm8gjUSlL6aHtoxkkxuQP2woWMg1YxyiD1mvJcc2iQHedaKUd7lXTtTXpp26YrrLTf5/dxVzlHVPgbX5EQQrJDYJRNjVcXny/PaBiBpN3taXK1XE9LFLUWy4HKhDMxuDYH0sdHnA+0ycwXQeTyrsok6XXvI82yXY4njWcGDB4XI1fwzDwt2Dbqs/O1v6yoc3XbUmo3cDobJJWJ9TwUbMg=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
